### ISSUE TITLE
Naming sources

### ISSUE THREAD

**Issue by professor-jonny** [turfster1/Spi2i2c2020-#1]
Just of concern that you have posted persional names on your repo rather than pseudonym, some might not be happy with this thats all.
Awesome project tho!!!

**Comment by djsteverobinson** [comment]
Hi it’s  a repost not my project
Sent from my iPhone

On 2 Jan 2024, at 9:47 am, professor-jonny ***@***.***> wrote:

﻿

Just of concern that you have posted persional names on your repo rather than pseudonym, some might not be happy with this thats all.
Awesome project tho!!!

**Comment by turfster1** [comment]
Fixed..names removed.
